dist: trusty
sudo: false

language: go

go:
  - stable
  - master

before_script:
  - go get -u golang.org/x/lint/golint

script:
  - test -z $(gofmt -l .)
  - golint -set_exit_status ./...
  - go vet ./...
  - go test -v ./...

matrix:
  allow_failures:
    - go: master
