language: go

go:
  - 1.6
  - 1.7
  - tip

before_script:
  - go get github.com/golang/lint/golint

script:
  - test -z $(gofmt -l .)
  - test -z $(golint ./...)
  - go vet ./...
  - go test -v ./...

matrix:
  allow_failures:
    - go: tip
